#!/usr/bin/env node
/**
 * dsh-powerbox — client.js 拼接脚本（无依赖，node scripts/build-client.mjs）。
 *
 * dsh-client-modules 每个包只装载一个客户端入口（package.json 的
 * `dsh.client` → `./client`），且浏览器 require 只解析共享模块表、不支持
 * 相对文件。所以四个功能 + 两个共享模块各自成文件维护（client/ 目录），
 * 由本脚本按固定顺序拼接成唯一的 client.js：
 *
 *   prelude（loader 注册 + 共享 React/E + TK 命名空间）
 *   → client/flags.js（开关读写）
 *   → client/toolkit-page.js（工具箱设置页）
 *   → client/permission-extras.js
 *   → client/plannotator.js
 *   → client/workspace-activity.js
 *   → client/sidebar-layout.js
 *   → footer（apply：创建 api → 依序 mount → 统一 disposer）
 *
 * 约定：client/ 下每个文件不写 import/export，注册到共享命名空间
 * `TK.features.<id> = { mount(ctx, api) }`；React / E / TK 由 prelude 提供。
 * 改动 client/ 下任何文件后必须重跑本脚本（profile 是 link: 安装时，
 * 生成的 client.js 会被 client-hmr 的 500ms 轮询热重载）。
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const PRELUDE = `/* dsh-powerbox client entry — GENERATED by scripts/build-client.mjs from client/*.js. DO NOT EDIT. */
window.__ModuleLoader__.load({
  id: 'dsh-powerbox',
  factory(require) {
    var _react = require('react');
    var React = (function (m) {
      if (m && typeof m.createElement === 'function') return m;
      if (m && m.default && typeof m.default.createElement === 'function') return m.default;
      return m;
    })(_react);
    var E = React.createElement;
    var TK = { entryId: 'toolkit', features: {}, pages: {} };
`

const FOOTER = `
    /* ===== footer: outer apply（外层统一引用各库）===== */
    var TK_ORDER = ['toolkit-page', 'permission-extras', 'plannotator', 'workspace-activity', 'sidebar-layout'];
    return {
      inject: ['slots', 'locale', 'remote', 'remote.settings', 'sessions', 'workspaces', 'connection', 'timer'],
      apply: function (ctx) {
        var api = TK.createFlags(ctx);
        var disposers = [];
        for (var i = 0; i < TK_ORDER.length; i += 1) {
          var feature = TK.features[TK_ORDER[i]];
          if (!feature || typeof feature.mount !== 'function') continue;
          var off = feature.mount(ctx, api);
          if (typeof off === 'function') disposers.push(off);
        }
        api.start();
        if (disposers.length > 0 || typeof api.stop === 'function') {
          ctx.effect(function () {
            return function () {
              api.stop();
              for (var j = 0; j < disposers.length; j += 1) {
                try { disposers[j](); } catch (e) { console.warn('toolkit: dispose failed', e); }
              }
            };
          }, 'toolkit: feature disposers');
        }
      },
    };
  },
});
`

const ORDER = [
  'client/flags.js',
  'client/toolkit-page.js',
  'client/permission-extras.js',
  'client/plannotator.js',
  'client/workspace-activity.js',
  'client/sidebar-layout.js',
]

const banner = (file) => `\n    /* ${'='.repeat(4)} source: ${file} ${'='.repeat(4)} */\n`

/**
 * 每个片段包一层 IIFE：所有片段共享 factory 的唯一函数作用域，裸块约束不了
 * `var`——曾因三个片段各声明 `var CSS` 互相覆盖，导致权限页/评审面板注入了
 * 别人的样式表（类名全部裸奔）。IIFE 让每个 `var` 天然局限在本片段内，
 * 跨片段共享只经 TK / prelude 的 React / E。
 */
const body = ORDER.map((file) =>
  banner(file) + '(function () {\n' + readFileSync(join(root, file), 'utf8') + '\n})();'
).join('\n')
const out = PRELUDE + body + FOOTER
writeFileSync(join(root, 'client.js'), out)

// 产物自检：确认每个库都注册了 mount，footer 恰好出现一次。
const missing = ['toolkit-page', 'permission-extras', 'plannotator', 'workspace-activity', 'sidebar-layout']
  .filter((key) => !out.includes(`TK.features['${key}'] =`) && !out.includes(`TK.features.${key} =`))
if (missing.length > 0) {
  console.error(`build-client: 缺少注册的功能: ${missing.join(', ')}`)
  process.exit(1)
}
console.log(`build-client: client.js 已生成（${(out.length / 1024).toFixed(1)} KiB）`)
